routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function ()
{
    Route::group(['middleware' => ['role:ADMIN']], function ()
    {
        Route::group(['middleware' => ['role:SUPER_ADMIN']], function ()
        {
            Route::resource('user', 'UserController', ['except' => ['show']]);
        });

        Route::resource('commodityTypes', 'CommodityTypeController');
        Route::resource('bentukSediaan', 'BentukSediaanController');
        Route::resource('produsen', 'ProdusenController');
    });

    Route::resource('commodities', 'CommodityController', ['except' => ['show']]);
    Route::post('commodities/search_commodity', 'CommodityController@SearchData');
	Route::get('commodities/search', ['as' => 'commodities.search', 'uses' => 'CommodityController@search']);
	Route::get('commodities/getCommodityQtyByID', ['as' => 'commodities.getCommodityQtyByID', 'uses' => 'CommodityController@getCommodityQtyByID']);
	Route::get('commodities/export', ['as' => 'commodities.export', 'uses' => 'CommodityController@export']);
    Route::post('commodities/import', ['as' => 'commodities.import', 'uses' => 'CommodityController@import']);

    Route::resource('transactions', 'TransactionsController');
    Route::get('transactions/create/{type}', ['as' => 'transactions.create', 'uses' => 'TransactionsController@create']);
    Route::post('transactions/store/items', ['as' => 'transactions.store.items', 'uses' => 'TransactionsController@storeItems']);
	Route::get('transactions/export/pdf', ['as' => 'transactions.export.pdf', 'uses' => 'TransactionsController@exportPdf']);
	Route::get('transactions/report/penjualan', ['as' => 'transactions.report_penjualan', 'uses' => 'TransactionsController@reportPenjualan']);
	Route::get('transactions/report/penjualan/search_date', ['as' => 'transactions.report_penjualan.search_date', 'uses' => 'TransactionsController@reportPenjualanSearch']);

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Transaction;
use App\Models\TransactionItems;
use App\Models\Commodity;

use App\Http\Requests\TransactionRequest;
use App\Http\Requests\TransactionItemsRequest;
use Illuminate\Http\Request;

use PDF;

class TransactionsController extends Controller
{
    public function index(Transaction $model)
    {
        return view('transactions.index', ['transactions' => $model->paginate(15)]);
    }

    public function create($type)
    {
        return view('transactions.create', ['transactions_type' => $type]);
    }

    public function reportPenjualan(Request $request, TransactionItems $model)
    {
        $total_penjualan = 0;
        $total_profit = 0;
        $start_date = date('Y-m-d');

        if ( $request->has('start_date') )
        {
            if ( empty($request->input('start_date')) )
            {
                return redirect()->route('transactions.report_penjualan');
            }

            $start_date = $request->input('start_date');
            $start_date = date('Y-m-d', strtotime($start_date));

            $object = $model->whereDate('created_at', $start_date)->paginate(10);

            // penjualan
            $total_penjualan = TransactionItems::whereDate('created_at', $start_date)->sum('sub_total');

            // profit
            $get_commodities_profit = TransactionItems::whereDate('created_at', $start_date)->get();

            foreach ($get_commodities_profit as $obj) {
                $profit = $obj->commodity->profit * $obj->qty;
                $total_profit = $total_profit + $profit;
            }

            if ( empty($model) )
            {
                return view('transactions.report_penjualan',
                [
                    'penjualans' => $object,
                    'total_profit' => $total_profit,
                    'total_penjualan' => $total_penjualan
                ]);
            }
            else
            {
                return view('transactions.report_penjualan',
                [
                    'penjualans' => $object,
                    'total_profit' => $total_profit,
                    'total_penjualan' => $total_penjualan
                ]);
            }
        }
        else
        {
            // penjualan
            $total_penjualan = TransactionItems::sum('sub_total');

            // profit
            $get_commodities_profit = TransactionItems::all();

            foreach ($get_commodities_profit as $object) {
                $profit = $object->commodity['profit'] * $object->qty;
                $total_profit = $total_profit + $profit;
            }

            return view('transactions.report_penjualan',
            [
                'penjualans' => $model->paginate(10),
                'total_profit' => $total_profit,
                'total_penjualan' => $total_penjualan
            ]);
        }
    }


    public function store(TransactionRequest $request, Transaction $model)
    {
        $data = $model->create($request->all());

        return response()->json($data);
    }

    public function storeItems(Request $request)
    {
        $requestData = $request->all();

        if ( is_array($requestData) )
        {
            foreach ($requestData as $data) {
                $model = new TransactionItems();

                $data = $model->create($data);
            }

            return response()->json([ 'success' => true, 'message' => 'Create Transaction Items Successfully' ]);
        }
        else
        {
            $model = new TransactionItems();

            $data = $model->create($requestData);

            return response()->json([ 'success' => true, 'message' => 'Create Transaction Items Successfully' ]);
        }
    }

    public function exportPdf(TransactionItems $model)
    {
        $pdf = PDF::loadView('transactions.partials.penjualan_export', ['penjualans' => $model->all() ]);

        set_time_limit(300);

        return $pdf->stream();

        // return $pdf->download('transactions.export.pdf');
    }

    public function edit(Transaction $transaction)
    {
        return view('transactions.edit', ['transaction' => $transaction]);
    }

    public function update(TransactionRequest $request, Transaction  $transaction)
    {
        $transaction->update($request->all());

        return redirect()->route('transactions.index')->withStatus(__('Transaction successfully updated.'));
    }

    public function destroy(Transaction  $transaction)
    {
        $transaction->delete();

        return redirect()->route('transactions.index')->withStatus(__('Transaction successfully deleted.'));
    }
}

resources/views/transactions/edit.blade.php
@extends('layouts.app', ['title' => __('Data Barang')])

@section('content')
    @include('commodities.partials.header', ['title' => __('Edit Data Barang')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Data Barang') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('commodities.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('commodities.update', $commodity) }}" autocomplete="off">
                            @csrf
                            @method('put')

                            <h6 class="heading-small text-muted mb-4">{{ __('Data information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group{{ $errors->has('code') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-code">{{ __('Kode Barang') }}</label>
                                            <input type="text" name="code" id="input-code" class="form-control form-control-alternative{{ $errors->has('code') ? ' is-invalid' : '' }}" placeholder="{{ __('Kode Barang') }}" value="{{ old('code', $commodity->code) }}" required autofocus>

                                            @if ($errors->has('code'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('code') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-name">{{ __('Nama Barang') }}</label>
                                            <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nama Barang') }}" value="{{ old('name', $commodity->name) }}" required autofocus>

                                            @if ($errors->has('name'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('stock') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-stock">{{ __('Stok') }}</label>
                                            <input type="number" min="0" name="stock" id="input-stock" class="form-control form-control-alternative{{ $errors->has('stock') ? ' is-invalid' : '' }}" placeholder="{{ __('Stok') }}" value="{{ old('stock', $commodity->stock) }}" required autofocus>

                                            @if ($errors->has('stock'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('stock') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('commodities_type_id') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-commodities_type_id">{{ __('Satuan') }}</label>
                                            <select name="commodities_type_id" id="input-commodities_type_id" class="form-control form-control-alternative{{ $errors->has('commodities_type_id') ? ' is-invalid' : '' }}" placeholder="{{ __('Pilih Satuan Barang') }}" value="{{ old('commodities_type_id', $commodity->commodities_type_id) }}" required autofocus>
                                                @foreach ($commodities_types as $commodities_type)
                                                    <option value="{{ $commodities_type->id }}">{{ $commodities_type->name }}</option>
                                                @endforeach
                                            </select>

                                            @if ($errors->has('commodities_type_id'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('commodities_type_id') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('buy_price') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-buy_price">{{ __('Harga Beli') }}
                                                <span class="badge badge-pill badge-primary">Satuan</span>
                                            </label>
                                            <input type="number" min="0" name="buy_price" id="input-buy-price" class="form-control form-control-alternative{{ $errors->has('buy_price') ? ' is-invalid' : '' }}" placeholder="{{ __('Harga Beli') }}" value="{{ old('buy_price', $commodity->buy_price) }}" required autofocus>

                                            @if ($errors->has('buy_price'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('buy_price') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('sell_price') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-sell_price">{{ __('Harga Jual') }}
                                                <span class="badge badge-pill badge-primary">Satuan</span>
                                            </label>
                                            <input type="number" min="0" name="sell_price" id="input-sell-price" class="form-control form-control-alternative{{ $errors->has('sell_price') ? ' is-invalid' : '' }}" placeholder="{{ __('Harga Jual') }}" value="{{ old('sell_price', $commodity->sell_price) }}" required autofocus>

                                            @if ($errors->has('sell_price'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('sell_price') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('profit') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-profit">{{ __('Profit') }}
                                                <span class="badge badge-pill badge-primary">Satuan</span>
                                            </label>
                                            <input type="number" name="profit" id="input-profit" class="form-control form-control-muted{{ $errors->has('profit') ? ' is-invalid' : '' }}" placeholder="{{ __('Profit') }}" value="{{ old('profit', $commodity->profit) }}" required autofocus>

                                            @if ($errors->has('profit'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('profit') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/transactions/index.blade.php
@extends('layouts.app', ['title' => __('Data Barang')])

@section('content')
    @include('layouts.headers.default')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Data Barang') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('commodities.create') }}" class="btn btn-sm btn-primary">{{ __('Tambah') }}</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('No') }}</th>
                                    <th scope="col">{{ __('Kode Barang') }}</th>
                                    <th scope="col">{{ __('Nama Barang') }}</th>
                                    <th scope="col">{{ __('Satuan') }}</th>
                                    <th scope="col">{{ __('Stok') }}</th>
                                    <th scope="col">{{ __('Harga Beli') }}</th>
                                    <th scope="col">{{ __('Harga Jual') }}</th>
                                    <th scope="col">{{ __('Profit') }}</th>
                                    <th scope="col">{{ __('Tanggal') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $no = 1;
                                @endphp
                                @foreach ($commodities as $commodity)
                                    <tr>
                                        <td>{{ $no }}</td>
                                        <td>{{ $commodity->code }}</td>
                                        <td>{{ $commodity->name }}</td>
                                        <td>{{ $commodity->commodityType->name }}</td>
                                        <td>{{ $commodity->stock }} pcs</td>
                                        <td>Rp. {{ $commodity->buy_price }}</td>
                                        <td>Rp. {{ $commodity->sell_price }}</td>
                                        <td>Rp. {{ $commodity->profit }}</td>
                                        <td>{{ $commodity->created_at->format('d/m/Y H:i') }}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    <form action="{{ route('commodities.destroy', $commodity) }}" method="post">
                                                        @csrf
                                                        @method('delete')

                                                        <a class="dropdown-item" href="{{ route('commodities.edit', $commodity) }}">{{ __('Edit') }}</a>
                                                        <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this Commodity?") }}') ? this.parentElement.submit() : ''">
                                                            {{ __('Delete') }}
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @php
                                        $no++;
                                    @endphp
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $commodities->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/transactions/report_penjualan.blade.php
@extends('layouts.app', ['title' => __('Laporan Penjualan')])

@section('content')
    @include('transactions.partials.header', ['title' => __('Laporan Penjualan')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            {{-- <div class="col-3">
                                <h3 class="mb-0">{{ __('Data Laporan Penjualan') }}</h3>
                            </div> --}}
                            <div class="col-sm-auto">

                                <form method="get" action="{{ route('transactions.report_penjualan') }}" autocomplete="off">
                                    {{-- @csrf --}}

                                            <div class="form-group">
                                                <div class="input-group input-group-alternative">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"><i class="ni ni-calendar-grid-58"></i></span>
                                                    </div>
                                                    <input class="form-control datepicker" name="start_date" placeholder="Pilih Tanggal" type="text" value="{{ old('start_date') }}" autofocus>
                                                </div>
                                            </div>

                                            <button type="submit" class="btn btn-info">{{ __('Cari') }}</button>

                                            {{-- <a href="{{ route('commodities.create') }}" class="btn btn-info">
                                                <i class="fas fa-search"></i> {{ __('Cari') }}
                                            </a> --}}
                                            <a href="{{ route('transactions.export.pdf') }}" class="btn btn-success" target="_blank">
                                                <i class="fas fa-print"></i> {{ __('Cetak') }}
                                            </a>
                                </form>
                            </div>
                                <div class="col-sm-8 text-right mt-2">
                                    <h3 class="mb-0 btn btn-sm btn-white">
                                        <span class="badge badge-pill badge-primary">Total</span> Rp. {{ number_format($total_penjualan, 0,',','.') }}
                                    </h3>

                                    <h3 class="mb-0 btn btn-sm btn-white">
                                        <span class="badge badge-pill badge-primary">Profit</span> Rp. {{ number_format($total_profit, 0,',','.') }}
                                    </h3>
                                </div>
                        </div>
                    </div>

                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('No') }}</th>
                                    <th scope="col">{{ __('Kode Barang') }}</th>
                                    <th scope="col">{{ __('Nama Barang') }}</th>
                                    <th scope="col">{{ __('Harga') }}</th>
                                    <th scope="col">{{ __('Jumlah') }}</th>
                                    <th scope="col">{{ __('Sub Total') }}</th>
                                    <th scope="col">{{ __('Profit') }}</th>
                                    <th scope="col">{{ __('Tanggal') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $no = 1;
                                @endphp
                                @if (!empty($penjualans))
                                    @foreach ($penjualans as $penjualan)
                                        <tr>
                                            <td>{{ $no }}</td>
                                            <td>{{ $penjualan->commodity->code }}</td>
                                            <td>{{ $penjualan->commodity->name }}</td>
                                            <td>Rp. {{ number_format($penjualan->commodity->buy_price, 0,',','.') }}</td>
                                            <td>{{ $penjualan->qty }} pcs</td>
                                            <td>Rp. {{ number_format($penjualan->sub_total, 0,',','.') }}</td>
                                            <td>Rp. {{ number_format($penjualan->commodity->profit, 0,',','.') }}</td>
                                            <td>{{ $penjualan->transactions->created_at->format('d/m/Y H:i') }}</td>
                                        </tr>
                                        @php
                                            $no++;
                                        @endphp
                                    @endforeach
                                @else
                                @endif
                            </tbody>
                        </table>
                    </div>

                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-center" aria-label="...">
                            {{ $penjualans->appends($_GET)->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

@push('js')
    <script src="{{ asset('argon') }}/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
@endpush