routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function ()
{
    Route::group(['middleware' => ['role:ADMIN']], function ()
    {
        Route::group(['middleware' => ['role:SUPER_ADMIN']], function ()
        {
            Route::resource('user', 'UserController', ['except' => ['show']]);
        });

        Route::resource('commodityTypes', 'CommodityTypeController');
        Route::resource('bentukSediaan', 'BentukSediaanController');
        Route::resource('produsen', 'ProdusenController');
    });

    Route::resource('commodities', 'CommodityController', ['except' => ['show']]);
    Route::post('commodities/search_commodity', 'CommodityController@SearchData');
	Route::get('commodities/search', ['as' => 'commodities.search', 'uses' => 'CommodityController@search']);
	Route::get('commodities/getCommodityQtyByID', ['as' => 'commodities.getCommodityQtyByID', 'uses' => 'CommodityController@getCommodityQtyByID']);
	Route::get('commodities/export', ['as' => 'commodities.export', 'uses' => 'CommodityController@export']);
    Route::post('commodities/import', ['as' => 'commodities.import', 'uses' => 'CommodityController@import']);

    Route::resource('transactions', 'TransactionsController');
    Route::get('transactions/create/{type}', ['as' => 'transactions.create', 'uses' => 'TransactionsController@create']);
    Route::post('transactions/store/items', ['as' => 'transactions.store.items', 'uses' => 'TransactionsController@storeItems']);
	Route::get('transactions/export/pdf', ['as' => 'transactions.export.pdf', 'uses' => 'TransactionsController@exportPdf']);
	Route::get('transactions/report/penjualan', ['as' => 'transactions.report_penjualan', 'uses' => 'TransactionsController@reportPenjualan']);
	Route::get('transactions/report/penjualan/search_date', ['as' => 'transactions.report_penjualan.search_date', 'uses' => 'TransactionsController@reportPenjualanSearch']);

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Http/Controllers/CommodityTypeController.php
<?php

namespace App\Http\Controllers;

use App\Models\CommodityType;
use App\Models\Commodity;
use App\Http\Requests\CommodityTypeRequest;

class CommodityTypeController extends Controller
{
    public function index(CommodityType $model)
    {
        return view('commodityTypes.index', ['commodityTypes' => $model->paginate(15)]);
    }

    public function create()
    {
        return view('commodityTypes.create');
    }

    public function store(CommodityTypeRequest $request, CommodityType $model)
    {
        $model->create($request->all());

        return redirect()->route('commodityTypes.index')->withStatus(__('Satuan Jenis Barang successfully created.'));
    }

    public function edit(CommodityType $commodityType)
    {
        return view('commodityTypes.edit', compact('commodityType'));
    }

    public function update(CommodityTypeRequest $request, CommodityType  $commodityType)
    {
        $commodityType->update($request->all());

        return redirect()->route('commodityTypes.index')->withStatus(__('Satuan Jenis Barang successfully updated.'));
    }

    public function destroy(CommodityType  $commodityType)
    {
        // check if commoditues_type already used in commodities
        $getCommoditiesType = Commodity::where('commodities_type_id', $commodityType->id)->get();

        if (count($getCommoditiesType) > 0)
        {
            return redirect()->route('commodityTypes.index')->with('status_error', 'Satuan Jenis Barang gagal di Hapus, Satuan sedang di gunakan!');
        }

        $commodityType->delete();

        return redirect()->route('commodityTypes.index')->withStatus(__('Satuan Jenis Barang successfully deleted.'));
    }
}

resources/views/commodityTypes/create.blade.php
@extends('layouts.app', ['title' => __('Jenis Satuan Barang')])

@section('content')
    @include('commodityTypes.partials.header', ['title' => __('Tambah Jenis Satuan Barang')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Jenis Satuan Barang') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('commodityTypes.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('commodityTypes.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Data information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/commodityTypes/edit.blade.php
@extends('layouts.app', ['title' => __('Jenis Satuan Barang')])

@section('content')
    @include('commodityTypes.partials.header', ['title' => __('Edit Jenis Satuan Barang')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Jenis Satuan Barang') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('commodityTypes.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('commodityTypes.update', $commodityType) }}" autocomplete="off">
                            @csrf
                            @method('put')

                            <h6 class="heading-small text-muted mb-4">{{ __('Data information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name', $commodityType->name) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/commodityTypes/index.blade.php
@extends('layouts.app', ['title' => __('Jenis Satuan Barang')])

@section('content')
    @include('layouts.headers.default')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Jenis Satuan Barang') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('commodityTypes.create') }}" class="btn btn-sm btn-primary">{{ __('Tambah') }}</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        @if (session('status') || session('status_error'))
                            <div class="alert {{ session('status_error') ? ' alert-danger' : 'alert-success' }} alert-dismissible fade show" role="alert">
                                {{ session('status_error') ? session('status_error') : session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('No') }}</th>
                                    <th scope="col">{{ __('Name') }}</th>
                                    <th scope="col">{{ __('Creation Date') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $no = 1;
                                @endphp
                                @foreach ($commodityTypes as $commodityType)
                                    <tr>
                                        <td>{{ $no }}</td>
                                        <td>{{ $commodityType->name }}</td>
                                        <td>{{ $commodityType->created_at->format('d/m/Y H:i') }}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    <form action="{{ route('commodityTypes.destroy', $commodityType) }}" method="post">
                                                        @csrf
                                                        @method('delete')

                                                        <a class="dropdown-item" href="{{ route('commodityTypes.edit', $commodityType) }}">{{ __('Edit') }}</a>
                                                        <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this commodityType?") }}') ? this.parentElement.submit() : ''">
                                                            {{ __('Delete') }}
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @php
                                        $no++;
                                    @endphp
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $commodityTypes->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection