routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function ()
{
    Route::group(['middleware' => ['role:ADMIN']], function ()
    {
        Route::group(['middleware' => ['role:SUPER_ADMIN']], function ()
        {
            Route::resource('user', 'UserController', ['except' => ['show']]);
        });

        Route::resource('commodityTypes', 'CommodityTypeController');
        Route::resource('bentukSediaan', 'BentukSediaanController');
        Route::resource('produsen', 'ProdusenController');
    });

    Route::resource('commodities', 'CommodityController', ['except' => ['show']]);
    Route::post('commodities/search_commodity', 'CommodityController@SearchData');
	Route::get('commodities/search', ['as' => 'commodities.search', 'uses' => 'CommodityController@search']);
	Route::get('commodities/getCommodityQtyByID', ['as' => 'commodities.getCommodityQtyByID', 'uses' => 'CommodityController@getCommodityQtyByID']);
	Route::get('commodities/export', ['as' => 'commodities.export', 'uses' => 'CommodityController@export']);
    Route::post('commodities/import', ['as' => 'commodities.import', 'uses' => 'CommodityController@import']);

    Route::resource('transactions', 'TransactionsController');
    Route::get('transactions/create/{type}', ['as' => 'transactions.create', 'uses' => 'TransactionsController@create']);
    Route::post('transactions/store/items', ['as' => 'transactions.store.items', 'uses' => 'TransactionsController@storeItems']);
	Route::get('transactions/export/pdf', ['as' => 'transactions.export.pdf', 'uses' => 'TransactionsController@exportPdf']);
	Route::get('transactions/report/penjualan', ['as' => 'transactions.report_penjualan', 'uses' => 'TransactionsController@reportPenjualan']);
	Route::get('transactions/report/penjualan/search_date', ['as' => 'transactions.report_penjualan.search_date', 'uses' => 'TransactionsController@reportPenjualanSearch']);

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Models/Commodity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Transaction;
use App\Models\TransactionItems;
use App\Models\CommodityType;
use App\Models\BentukSediaan;
use App\Models\Produsen;

/**
 * Class Commodity.
 *
 * @package namespace App\Models;
 */
class Commodity extends Model
{
    public $table = 'commodities';

    protected $primaryKey = 'id';

    public $incrementing = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
		'code',
        'name',
        'bentuk_sediaans_id',
        'commodities_type_id',
        'stock',
        'buy_price',
        'sell_price',
        'profit',
        'produsens_id',
        'created_at'
    ];

    #region transactions
    public function transactions()
    {
        return $this->hasMany('App\Models\Transaction');
    }
    #endregion

    #region transactionItems
    public function transactionItems()
    {
        return $this->hasMany('App\Models\TransactionItems');
    }
    #endregion

    #region commodityType
    public function commodityType()
    {
        return $this->belongsTo('App\Models\CommodityType', 'commodities_type_id');
    }
    #endregion

    #region bentukSediaan
    public function bentukSediaan()
    {
        return $this->belongsTo('App\Models\BentukSediaan', 'bentuk_sediaans_id');
    }
    #endregion

    #region produsen
    public function produsen()
    {
        return $this->belongsTo('App\Models\Produsen', 'produsens_id');
    }
    #endregion
}

app/Models/CommodityType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Commodity;

/**
 * Class CommodityType.
 *
 * @package namespace App\Models;
 */
class CommodityType extends Model
{
    public $table = 'commodities_types';

    protected $primaryKey = 'id';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    public $incrementing = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    #region commodity
    public function commodity()
    {
        return $this->hasOne('App\Models\Commodity', 'commodities_type_id');
    }
    #endregion
}

app/Http/Controllers/CommodityController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Commodity;
use App\Models\CommodityType;
use App\Http\Requests\CommodityRequest;

use App\Exports\CommodityExport;
use App\Imports\CommodityImport;
use App\Models\BentukSediaan;
use App\Models\Produsen;
use Maatwebsite\Excel\Facades\Excel;

class CommodityController extends Controller
{
    private $maxRow = 15;

    public function index(Commodity $model)
    {
        $data['no'] = 1;

        $data['commodities'] = $model->paginate($this->maxRow);

        $data['total_page'] = $data['commodities']->lastPage();

        $data['max_row'] = $this->maxRow;

        return view('commodities.index', $data);
    }

    public function export(Request $request)
    {
        if ($request->has('start_date') && $request->has('end_date'))
        {
            $start_date = $request->input('start_date');
            $end_date = $request->input('end_date');

            return Excel::download(new CommodityExport($start_date, $end_date), 'data_obat.xlsx');
        }
    }

    public function import(Request $request)
    {
        if ($request->hasFile('file'))
        {
            Excel::import(new CommodityImport, $request->file('file'));

            return redirect('/commodities')->with('success', 'Barang Berhasil di Import.');
        }
    }

    public function create()
    {
        $commodityType = CommodityType::all();
        $bentukSediaan = BentukSediaan::all();
        $produsen = Produsen::all();

        return view('commodities.create',
        [
            'commodities_types' => $commodityType,
            'bentuk_sediaans' => $bentukSediaan,
            'produsens' => $produsen
        ]);
    }

    public function store(CommodityRequest $request, Commodity $model)
    {
        $model->create($request->all());

        return redirect()->route('commodities.index')->withStatus(__('Barang successfully created.'));
    }

    public function edit(Commodity $commodity)
    {
        $commodityType = CommodityType::all();
        $bentukSediaan = BentukSediaan::all();
        $produsen = Produsen::all();

        return view(
            'commodities.edit',
            [
                'commodity' => $commodity,
                'commodities_types' => $commodityType,
                'bentuk_sediaans' => $bentukSediaan,
                'produsens' => $produsen
            ]
        );
    }

    public function update(CommodityRequest $request, Commodity  $commodity)
    {
        $commodity->update($request->all());

        // Session::flash('success_message', 'Barang successfully updated.');

        // return redirect()->back();

        return redirect()->route('commodities.index')->with('success_message', 'Barang successfully updated.');
    }

    public function destroy(Commodity  $commodity)
    {
        $commodity->delete();

        return redirect()->route('commodities.index')->with('success_message', 'Barang successfully deleted.');
    }

    public function search(Request $request)
    {
            $query = $request->get('query');
            $id = $request->get('id');

            if ($query != '')
            {
                $commodities = Commodity::select("*")
                        ->orWhere('code', 'LIKE', '%'.$query.'%')
                        ->orWhere('name', 'LIKE', '%'.$query.'%')
                        ->get();
            }
            else if ($id != '')
            {
                $commodities = Commodity::find($id);
            }
            else
            {
                $commodities = Commodity::all();
            }

            return response()->json($commodities);
    }

    public function getCommodityQtyByID(Request $request)
    {
        $id = $request->get('id');

        try
        {
            $commodity = Commodity::where('id', $id)->pluck('stock');

            if (count($commodity) != 0)
            {
                return response()->json($commodity[0]);
            }
        }
        catch (Exception $exception)
        {
            return response()->json(['error' => $exception->getMessage()], 500);
        }
    }

    public function SearchData(Request $req)
    {
        $rs_data = Commodity::from('commodities as a')
            ->join('commodities_types', 'commodities_types.id', '=', 'a.commodities_type_id')
            ->join('bentuk_sediaans', 'bentuk_sediaans.id', '=', 'a.bentuk_sediaans_id')
            ->join('produsens', 'produsens.id', '=', 'a.produsens_id')
            ->select(
            'a.*',
            'commodities_types.id as commodities_type_id',
            'bentuk_sediaans.id as bentuk_sediaans_id',
            'produsens.id as produsens_id',
            'commodities_types.name as commodityType',
            'bentuk_sediaans.name as bentukSediaan',
            'produsens.name as produsen'
            );

        $textSearch = $req->text_search;
        $filterSearch = $req->filter_search;
        $sortSearch = $req->sort_search;

        $rs_data->where(function ($q) use ($textSearch, $filterSearch)
        {
            if ($filterSearch != "" || $filterSearch != null)
            {
                $q->Where('a.' . $filterSearch, 'LIKE', '%' . $textSearch . '%');
            }
            else
            {
                $q->where('a.name', 'LIKE', '%' . $textSearch . '%');
                $q->orWhere('a.code', 'LIKE', '%' . $textSearch . '%');
            }
        });

        if ($filterSearch != "" || $filterSearch != null)
        {
            if ($sortSearch != "" || $sortSearch != null)
            {
                if ($sortSearch == "first")
                {
                    $qrData = $rs_data->orderBy('a.created_at', 'asc');
                }
                else if ($sortSearch == "last")
                {
                    $qrData = $rs_data->orderBy('a.created_at', 'desc');
                }
                else
                {
                    $qrData = $rs_data->orderBy($filterSearch, $sortSearch);
                }
            }
            else
            {
                $qrData = $rs_data->orderBy($filterSearch, 'asc');
            }
        }
        else if ($sortSearch != "" || $sortSearch != null)
        {
            if ($sortSearch == "first")
            {
                $qrData = $rs_data->orderBy('a.created_at', 'asc');
            }
            else if ($sortSearch == "last")
            {
                $qrData = $rs_data->orderBy('a.created_at', 'desc');
            }
            else
            {
                $qrData = $rs_data->orderBy('a.code', $sortSearch);
            }
        }

        $qrData = $rs_data->paginate($this->maxRow);

        $data['rs_data'] = $qrData;
        $data['pagination'] =  (string) $qrData->links();

        return json_encode($data);
    }
}

resources/views/commodities/create.blade.php
@extends('layouts.app', ['title' => __('Data Barang')])

@section('content')
    @include('commodities.partials.header', ['title' => __('Tambah Data Barang')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Data Barang') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('commodities.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('commodities.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Data information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group{{ $errors->has('code') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-code">{{ __('Kode Barang') }}</label>
                                            <input type="text" name="code" id="input-code" class="form-control form-control-alternative{{ $errors->has('code') ? ' is-invalid' : '' }}" placeholder="{{ __('Kode Barang') }}" value="{{ old('code') }}" required autofocus>

                                            @if ($errors->has('code'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('code') }}</strong>
                                                </span>
                                            @endif

                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-name">{{ __('Nama Barang') }}</label>
                                            <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nama Barang') }}" value="{{ old('name') }}" required autofocus>

                                            @if ($errors->has('name'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </span>
                                            @endif

                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="form-group{{ $errors->has('bentuk_sediaans_id') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-bentuk_sediaans_id">{{ __('Bentuk Sediaan') }}</label>
                                            <select name="bentuk_sediaans_id" id="input-bentuk_sediaans_id" class="form-control form-control-alternative{{ $errors->has('bentuk_sediaans_id') ? ' is-invalid' : '' }}" placeholder="{{ __('Pilih Bentuk Sediaan') }}" value="{{ old('bentuk_sediaans_id') }}" required autofocus>
                                                @foreach ($bentuk_sediaans as $bentuk_sediaan)
                                                    <option value="{{ $bentuk_sediaan->id }}">{{ $bentuk_sediaan->name }}</option>
                                                @endforeach
                                            </select>

                                            @if ($errors->has('bentuk_sediaans_id'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('bentuk_sediaans_id') }}</strong>
                                                </span>
                                            @endif

                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="form-group{{ $errors->has('produsens_id') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-produsens_id">{{ __('Produsen') }}</label>
                                            <select name="produsens_id" id="input-produsens_id" class="form-control form-control-alternative{{ $errors->has('produsens_id') ? ' is-invalid' : '' }}" placeholder="{{ __('Pilih Bentuk Sediaan') }}" value="{{ old('produsens_id') }}" required autofocus>
                                                @foreach ($produsens as $produsen)
                                                    <option value="{{ $produsen->id }}">{{ $produsen->name }}</option>
                                                @endforeach
                                            </select>

                                            @if ($errors->has('produsens_id'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('produsens_id') }}</strong>
                                                </span>
                                            @endif

                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('stock') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-stock">{{ __('Stok') }}</label>
                                            <input type="number" min="0" name="stock" id="input-stock" class="form-control form-control-alternative{{ $errors->has('stock') ? ' is-invalid' : '' }}" placeholder="{{ __('Stok') }}" value="{{ old('stock') }}" required autofocus>

                                            @if ($errors->has('stock'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('stock') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('commodities_type_id') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-commodities_type_id">{{ __('Satuan') }}</label>
                                            <select name="commodities_type_id" id="input-commodities_type_id" class="form-control form-control-alternative{{ $errors->has('commodities_type_id') ? ' is-invalid' : '' }}" placeholder="{{ __('Pilih Satuan Barang') }}" value="{{ old('commodities_type_id') }}" required autofocus>
                                                @foreach ($commodities_types as $commodities_type)
                                                    <option value="{{ $commodities_type->id }}">{{ $commodities_type->name }}</option>
                                                @endforeach
                                            </select>

                                            @if ($errors->has('commodities_type_id'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('commodities_type_id') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('buy_price') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-buy_price">{{ __('Harga Beli') }}
                                                <span class="badge badge-pill badge-primary">Satuan</span>
                                            </label>
                                            <input type="number" min="0" name="buy_price" id="input-buy-price" class="form-control form-control-alternative{{ $errors->has('buy_price') ? ' is-invalid' : '' }}" placeholder="{{ __('Harga Beli') }}" value="{{ old('buy_price') }}" required autofocus>

                                            @if ($errors->has('buy_price'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('buy_price') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group{{ $errors->has('sell_price') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="input-sell_price">{{ __('Harga Jual') }}
                                                <span class="badge badge-pill badge-primary">Satuan</span>
                                            </label>
                                            <input type="number" min="0" name="sell_price" id="input-sell-price" class="form-control form-control-alternative{{ $errors->has('sell_price') ? ' is-invalid' : '' }}" placeholder="{{ __('Harga Jual') }}" value="{{ old('sell_price') }}" required autofocus>

                                            @if ($errors->has('sell_price'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('sell_price') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        @if ( auth()->user()->hasRole("SUPER_ADMIN") )
                                            <div class="form-group{{ $errors->has('profit') ? ' has-danger' : '' }}">
                                                <label class="form-control-label" for="input-profit">{{ __('Profit') }}
                                                    <span class="badge badge-pill badge-primary">Satuan</span>
                                                </label>
                                                <input type="number" name="profit" id="input-profit" class="form-control form-control-muted{{ $errors->has('profit') ? ' is-invalid' : '' }}" placeholder="{{ __('Profit') }}" value="{{ old('profit') }}" required autofocus>

                                                @if ($errors->has('profit'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('profit') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                        @else
                                            <input type="hidden" name="profit" id="input-profit" class="form-control form-control-muted{{ $errors->has('profit') ? ' is-invalid' : '' }}" placeholder="{{ __('Profit') }}" value="{{ old('profit') }}" required autofocus>
                                        @endif
                                    </div>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection